{"uuid":"76c81224-8dfc-4778-bc01-f937f3f4b524","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Cannot access file cypress/e2e/spreadsheet/userData.xlsx\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"Error: The following error originated from your test code, not from Cypress.\n\n  > Cannot access file cypress/e2e/spreadsheet/userData.xlsx\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at read_binary (webpack://cypress-learning-b15/./node_modules/xlsx/xlsx.mjs:3234:0)\n    at readSync (webpack://cypress-learning-b15/./node_modules/xlsx/xlsx.mjs:23811:64)\n    at Module.readFileSync (webpack://cypress-learning-b15/./node_modules/xlsx/xlsx.mjs:23851:0)\n    at eval (webpack://cypress-learning-b15/./cypress/e2e/convertxlsx.cy.js:9:20)\n    at eval (http://localhost:59194/__cypress/tests?p=cypress\\e2e\\convertxlsx.cy.js:24921:3)\n    at eval (http://localhost:59194/__cypress/tests?p=cypress\\e2e\\convertxlsx.cy.js:24923:12)\n    at eval (<anonymous>)"},"stage":"finished","steps":[],"attachments":[{"name":"convertxlsx.cy.js:2025-04-16T03:11:17.831Z","type":"image/png","source":"e4cd3dcc-3194-4d81-bf46-4e22f3ca37b2-attachment.png"},{"name":"video recording","type":"video/mp4","source":"a80006af-f7bb-4f7d-bbf8-348f25f8c3e3-attachment.mp4"}],"parameters":[],"labels":[{"name":"package","value":"cypress.e2e.convertxlsx.cy.js"}],"links":[],"start":1744773077391,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1744773078008}